services:

  db:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - 5433:5432
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - vehicle
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "app", "-d", "db" ]
      interval: 5s
      retries: 5


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./db-postgres/pgadmin:/root/.pgadmin
    ports:
      - 8090:80
    networks:
      - vehicle
    restart: unless-stopped

  backend:
    image: coop/payment:latest
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/payment
      QUARKUS_DATASOURCE_USERNAME: payment
      QUARKUS_DATASOURCE_PASSWORD: payment
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - vehicle


networks:
  vehicle:
    name: quarkus-vehicle-network
    driver: bridge